spring.application.name=timetable

# Aiven MySQL Cloud Database Connection
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:mysql://mysql-2fe3e6d3-gimaya222-6d31.c.aivencloud.com:12525/defaultdb?useSSL=true&trustServerCertificate=true&allowPublicKeyRetrieval=true}
spring.datasource.username=${JDBC_DATABASE_USERNAME:avnadmin}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080
