spring.application.name=timetable

spring.datasource.url=jdbc:mysql://localhost:3306/foe_timetable_scheduler
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:Gimaya@1234}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080
